coverage:
  precision: 2
  round: nearest
  range: "50...90"
  ignore:
    - "pyclits/empirical_model.py"
  status:
    project:
      default:
        enabled: yes
        target: auto
        threshold: 5%
    patch: off
